---
title: "GSE156455"
output:
  html_document:
    df_print: paged
---

# Install packages

```{r}
install.packages('Seurat')
install.packages('dplyr')
install.packages('RColorBrewer')
install.packages('ggplot2')
```

# Load installed packages

```{r}
library(Seurat)
library(dplyr)
library(Matrix)
library(RColorBrewer)
library(ggplot2)
```

# Setup datasets

```{r}
barcodes = read.table("datasets/GSE156455_barcodes_main.tsv",                sep = "\t")
features = read.table("datasets/GSE156455_features_main.tsv",                sep = "\t", row.names = 1)
metadata = read.table("datasets/GSE156455_metadata_main.tsv", header = TRUE, sep = "\t", row.names = 1)
tsne     = read.table("datasets/GSE156455_tsne_main.tsv",     header = TRUE, sep = "\t", row.names = 1)
matrix   = Matrix::readMM("datasets/GSE156455_matrix_main.mtx")
```

```{r}
tsne_with_meta = cbind(tsne, metadata)
```

```{r}
columns = c("label", "x", "y")
centers = data.frame(matrix(nrow = 0, ncol = length(columns))) 
colnames(centers) = columns
types = unique(metadata$subtype)

for (type in types) {
  x = mean(tsne_with_meta$tSNE_2[tsne_with_meta$subtype == type])
  y = mean(tsne_with_meta$tSNE_1[tsne_with_meta$subtype == type])
  centers[type,] = list(type, x, y)
}
```


```{r}
ggplot() +
  geom_point(size = 0.01, mapping = aes(tSNE_2, tSNE_1, colour = type), data = tsne_with_meta, show.legend = FALSE) +
  geom_text(mapping = aes(x, y, label = label), data = centers, check_overlap = TRUE)
ggsave('clusters.png', width=13, height = 10)
```

```{r}
feature_index = which(rownames(features) == 'FBgn0038498')
expressions = matrix[feature_index, ]
max_expression = max(expressions)
expressoins_regularized = sapply(expressions, function(v) {
  return (v / max_expression)
})
tsne_with_meta_and_expression = cbind(tsne_with_meta, expressoins_regularized)

ggplot() +
  geom_point(
    size = 3,
    mapping = aes(tSNE_2, tSNE_1),
    color = 'grey',
    data = tsne_with_meta,
    show.legend = FALSE
  ) +
  geom_point(
    size = 3,
    mapping = aes(tSNE_2, tSNE_1, alpha = expressoins_regularized),
    data = tsne_with_meta_and_expression[tsne_with_meta_and_expression$expressoins_regularized != 0.0,],
    color = 'purple',
    show.legend = FALSE
  ) +
  geom_text(
    mapping = aes(x, y, label = label),
    data = centers,
    check_overlap = TRUE
  )
ggsave('expression.png', width = 39, height = 30)
```

```{r}
times = unique(metadata$time)
for (time in times) {
  ggplot() +
    geom_point(
      size = 3,
      mapping = aes(tSNE_2, tSNE_1),
      color = 'grey',
      data = tsne_with_meta,
      show.legend = FALSE
    ) +
    geom_point(
      size = 3,
      mapping = aes(tSNE_2, tSNE_1, alpha = expressoins_regularized),
      data = tsne_with_meta_and_expression[tsne_with_meta_and_expression$expressoins_regularized != 0.0, ][tsne_with_meta_and_expression$time == time, ],
      color = 'purple',
      show.legend = FALSE
    ) +
    geom_text(
      mapping = aes(x, y, label = label),
      data = centers,
      check_overlap = TRUE
    )
  ggsave(sprintf('expression-%s.png', time),
         width = 39,
         height = 30)
}
```


